### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by madeinjam** [jfromaniello/parse-links#2]
Hi!

How do you run tests?

I tried mocha and this happens:

``` bash
  ․

  0 passing (4ms)
  1 failing

  1) parse-links parse the links!:
     TypeError: Cannot call method 'eql' of undefined
      at Context.<anonymous> (/Users/jam/Documents/Playground/parse-links/test/tests.js:11:25)
      at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:221:32)
      at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:374:10)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:452:12
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:299:14)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:309:7
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:247:23)
      at Object._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)
```

Thank you!

**Comment by madeinjam** [comment]
Never mind, I installed `chai` and it worked.

Thanks!

**Comment by jfromaniello** [comment]
just to be clear this module doesn't use chai, it uses mocha and should. To run tests you should execute `npm test`
